apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dev-testgo-destination
spec:
  host: dev-testgo-service
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2