apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-go
spec:
  hosts:
  - "reviews"
  http:
  - headers:
      request:
        set:
          test: "true"
    route:
    - destination:
        host: dev-testgo-service # 一定需要對應 service name
        subset: v2
  - route:
    - destination:
        host: dev-testgo-service # 一定需要對應 service name
        subset: v1
        port:
          number: 8080